version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://gastric_ai_user:secure_password@db:5432/gastric_ai
      - FASTAPI_URL=http://backend:8000/predict/
    depends_on:
      - db
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gastric
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
